accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup', views.signup_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views
app_name = "articles"
urlpatterns = [
    path('', views.articles_list, name='list'),
    path('create', views.create_post, name='create'),
    path('<url>', views.articles_in, name="articin"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
# app_name = 'blog'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('required/', views.required),
    path('profiles/', include('profiles.urls')),
    path('', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views
from .views import UserEditProfile

app_name = 'profiles'

urlpatterns = [
    path('users/', views.user_profile, name='userprof'),
    path('profilesettings/', views.UserEditProfile.as_view(), name='UserEditProfile'),
    path('information/', views.information, name='information'),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=100)
    url = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(default='default.jpg', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):  # For Getting Post Title and Put it in Admin Article Page
        return self.title

    def short_description(self):  # For Showing 100 Character of Text in main article page
        return self.body[:100] + '...'

    def thumbnail_def(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            return "\media\default.jpg"

profiles/models.py
from django.contrib.auth.models import models

class UpdateInfo(models.Model):
    realname = models.CharField(max_length=100)
    age = models.CharField(max_length=1000)
    desc = models.TextField()

articles/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'url', 'body', 'thumbnail']

profiles/forms.py
from django import forms

from .models import UpdateInfo


class Info(forms.ModelForm):
    class Meta:
        model = UpdateInfo
        fields = ['realname' , 'age', 'desc']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as Mlogin , logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Mlogin(request,user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        login = AuthenticationForm(data=request.POST)
        if login.is_valid():
            user = login.get_user()
            Mlogin(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
    else:
        login = AuthenticationForm()
    return render(request, 'login.html', {'login': login})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

articles/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms


def articles_list(request):
    articles = models.Article.objects.all().order_by('-date')
    return render(request, 'articles/articles.html', {'articles': articles})


def articles_in(request, url):
    inarticle = models.Article.objects.get(url=url)
    return render(request, 'articles/posts.html', {'inpost': inarticle})


@login_required(login_url='/accounts/login')
def create_post(request):
    if request.method == 'POST':
        cpost = forms.CreatePost(request.POST,request.FILES)
        if cpost.is_valid:
            instance = cpost.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        cpost = forms.CreatePost()
        return render(request, 'articles/createpost.html', {'cpost': cpost})

blog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    return render(request, "about.html")

def home(request):
    return render(request, "home.html")

def required(request):
    return render(request, 'required.html')

profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from . import forms, models


@login_required(login_url='/accounts/login')
def user_profile(request):
    data = models.UpdateInfo.objects.all()
    return render(request, 'userprofile.html', {'data': data})


class UserEditProfile(generic.UpdateView):
    form_class = UserChangeForm
    template_name = 'usersettings.html'
    success_url = reverse_lazy('userprofile.html')

    def get_object(self):
        return self.request.user


def information(request):
    if request.method == 'POST':
        form = forms.Info(request.POST)
        if form.is_valid():
            form.save()
            return redirect('profiles:userprof')
    else:
        form = forms.Info()
    return render(request, 'info.html', {'form': form})

accounts/templates/login.html
{% extends 'base.html' %}
{% block title %}
Title S
{% endblock %}
{% block content %}
<h1>Sign Up</h1>
<div class="login_page">
    <form class="reglog_form" action="{% url 'accounts:login' %}" method="POST">
        {{login}}
        {% csrf_token %}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {%endif%}
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% block title %}
Title S
{% endblock %}
{% block content %}
<h1>Sign Up</h1>
<div class="signup_page">
    <form class="reglog_form" action="/accounts/signup" method="POST">
        {{form}}
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}

articles/templates/articles/articles.html
{% extends 'base.html' %}
{% block title %}
TIT
{% endblock %}
{% block content %}
<h1>Articles Page</h1>
<div class="articles-list">
  {% for article in articles %}
  <div class="articles-list-sub">
  <h2>
    <a href="{% url 'articles:articin' url=article.url %}">{{article.title}}</a>
  </h2>
  <center><img src="{{article.thumbnail_def}}"/></center>
  <p class="short_des">{{article.short_description}}</p>
  <pc class="author">{{article.author}}</pc>
  <p class="date">{{article.date}}</p>
</div>
{% endfor %}
</div>
{% endblock %}

articles/templates/articles/createpost.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
POSTS
{% endblock %}
{% block content %}
<h1>Posts</h1>
<div class="create_post_page">
    <form class="create-post" action="{%url 'articles:create'%}" method="POST" enctype="multipart/form-data">
    {{cpost}}
    {% csrf_token %}
    <input type="submit" name="" value="send post">
</form>
</div>

<script src="{% static 'urlify.js' %}"></script>
{% endblock %}

articles/templates/articles/posts.html
{% extends 'base.html' %}
{% block title %}
POSTS
{% endblock %}
{% block content %}
<h1>Posts</h1>
<div class="article">
    <div class="posts-details">
        <h2>{{inpost.title}}</h2>
        <center><img src="{{inpost.thumbnail_def}}"/></center>
        <p>{{inpost.body}}</p>
        <p>{{inpost.date}}</p>
        <p>{{inpost.author}}</p>
        <p>You Are in URL: {{inpost.url}}</p>
        <a href="/articles">Back</a>
    </div>
</div>
{% endblock %}

profiles/templates/info.html
{% extends 'base.html' %}
{% block title %}
Update Information
{% endblock %}
{% block content %}
<div class="reglog_form">
    <h1>Update Information</h1>
    <div class="info-form">
    <form method="post" action="{% url 'profiles:information' %}">
        {{ form }}
        {% csrf_token %}
        <input type="submit" value="submit">
    </form>
    </div>
</div>
{% endblock %}

profiles/templates/userprofile.html
{% extends 'base.html' %}

{% block content %}


<div class="user-p">
    <ul>
        <p>User Group:</p>
        {% if user.is_superuser %}
        <p>SuperUser</p>
        {%else%}
        <p>User</p>
        {%endif%}
        <br/>
        <p>Username:</p>
        <p>{{user}}</p>
    <br/>
    {% for data in data %}
        <p>Data Readed from Update_Info Table in Database</p>
        <br/>
    <p>{{ data.realname }}</p>
        <br/>
        <p>{{ data.age }}</p>
        <br/>
        <p>{{ data.desc }}</p>
    {% endfor %}
    </ul>
</div>


{% endblock %}

profiles/templates/usersettings.html
{% extends 'base.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% block content %}
<div class="reglog_form">
    <h1>Edit Profile (Work in Progress)</h1>
    <div class="edit-form">
        <form method="post">
    {{ form }}
            {% csrf_token %}
            <input type="submit" value="submit">
        </form>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/userprofile.css">
    <meta charset="UTF-8">
    <title>
       {% block title %}
        {% endblock %}
    </title>
</head>
<body>
<header>
    
    <nav>
        
        <ul>
            {% if user.is_superuser %}
            <div class="dropdown">
                <a class="dropbtn">Admin Menu</a>
                <div class="dropdown-content">
                  <a href="/admin" target="_blank">Admin Panel</a>
                  <a href="/admin/articles/article/" target="_blank">Articles Section</a>
                  <a href="/admin/auth/user/" target="_blank">Users Section</a>
                </div>
              </div> 
            {%else%}
            {%endif%}
            {% if user.is_authenticated %}
            <div class="dropdown">
                <a class="dropbtn">User Menu</a>
                <div class="dropdown-content">
                    <a href="{% url 'profiles:userprof' %}">Profile</a>
                  <a href="{% url 'articles:create' %}">Create Post</a>
                  <a href="{% url 'articles:list' %}">Articles</a>
                    <a href="{% url 'profiles:UserEditProfile' %}">Edit Profile</a>
                    <a href="{% url 'profiles:information' %}">Update Information</a>
                </div>
              </div> 
            <li>
                <form class="logout" action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Exit</button>
                </form>
            </li>
            {%else%}
            <li>
                <a href="{%url 'accounts:login'%}">Login</a>
            </li>
            <li>
                <a href="{%url 'accounts:signup'%}">SignUp</a>
            </li>
            {%endif%}
            
        </ul>
    </nav>
    <a class="logo" href="/">LOGO</a>
</header>
<div class="wrapper">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

templates/required.html
{% extends 'base.html' %}
{% block title %}
POSTS
{% endblock %}
{% block content %}
<h1>Posts</h1>
<div class="content">
   <h3>
       You Need to Login or Sign Up
   </h3>
   <a href="/accounts/signup">Sign Up</a>
   <a href="/accounts/login">Sign In</a>
</div>

{% endblock %}